name: Publish Package

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build package
              run: bun run build

            - name: Publish package
              run: bun publish --registry=https://npm.pkg.github.com/
              env:
                  NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
